name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make | 
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y jq
    

    - name: Run check
      run: make check

    - name: Run clean
      run: make clean
